"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Union
from .base import EmbeddingFunction
from .registry import register
from .utils import IMAGES, TEXT

@register("colpali")
class ColPaliEmbeddings(EmbeddingFunction):
    """
    An embedding function that uses the ColPali engine for
    multimodal multi-vector embeddings.

    This embedding function supports ColPali models, producing multivector outputs
    for both text and image inputs.

    Parameters
    ----------
    model_name : str
        The name of the model to use (e.g., "Metric-AI/ColQwen2.5-3b-multilingual-v1.0")
        Supports models based on these engines:
        - ColPali: "vidore/colpali-v1.3" and others
        - ColQwen2.5: "Metric-AI/ColQwen2.5-3b-multilingual-v1.0" and others
        - ColQwen2: "vidore/colqwen2-v1.0" and others
        - ColSmol: "vidore/colSmol-256M" and others

    device : str
        The device for inference (default "auto").
    dtype : str
        Data type for model weights (default "bfloat16").
    use_token_pooling : bool
        DEPRECATED. Whether to use token pooling. Use `pooling_strategy` instead.
    pooling_strategy : str, optional
        The token pooling strategy to use, by default "hierarchical".
        - "hierarchical": Progressively pools tokens to reduce sequence length.
        - "lambda": A simpler pooling that uses a custom `pooling_func`.
    pooling_func: typing.Callable, optional
        A function to use for pooling when `pooling_strategy` is "lambda".
    pool_factor : int
        Factor to reduce sequence length if token pooling is enabled (default 2).
    quantization_config : Optional[BitsAndBytesConfig]
        Quantization configuration for the model. (default None, bitsandbytes needed)
    batch_size : int
        Batch size for processing inputs (default 2).
    offload_folder: str, optional
        Folder to offload model weights if using CPU offloading (default None). This is
        useful for large models that do not fit in memory.
    """
    model_name: str = ...
    device: str = ...
    dtype: str = ...
    use_token_pooling: bool = ...
    pooling_strategy: Optional[str] = ...
    pooling_func: Optional[Any] = ...
    pool_factor: int = ...
    quantization_config: Optional[Any] = ...
    batch_size: int = ...
    offload_folder: Optional[str] = ...
    _model = ...
    _processor = ...
    _token_pooler = ...
    _vector_dim = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def ndims(self): # -> Any:
        """
        Return the dimension of a vector in the multivector output (e.g., 128).
        """
        ...
    
    def generate_text_embeddings(self, text: TEXT) -> List[List[List[float]]]:
        """
        Generate embeddings for text input.
        """
        ...
    
    def generate_image_embeddings(self, images: IMAGES) -> List[List[List[float]]]:
        """
        Generate embeddings for a batch of images.
        """
        ...
    
    def compute_query_embeddings(self, query: Union[str, IMAGES], *args, **kwargs) -> List[List[List[float]]]:
        """
        Compute embeddings for a single user query (text only).
        """
        ...
    
    def compute_source_embeddings(self, images: IMAGES, *args, **kwargs) -> List[List[List[float]]]:
        """
        Compute embeddings for a batch of source images.

        Parameters
        ----------
        images : Union[str, bytes, List, pa.Array, pa.ChunkedArray, np.ndarray]
            Batch of images (paths, URLs, bytes, or PIL Images).
        """
        ...
    


