"""
This type stub file was generated by pyright.
"""

import numpy as np
import PIL
from typing import Any, ClassVar, List, Optional, TYPE_CHECKING, Union
from pathlib import Path
from .base import EmbeddingFunction
from .registry import register
from .utils import IMAGES, TEXT

if TYPE_CHECKING:
    ...
VOYAGE_TOTAL_TOKEN_LIMITS = ...
BATCH_SIZE = ...
def is_valid_url(text): # -> bool:
    ...

VIDEO_EXTENSIONS = ...
def is_video_url(url: str) -> bool:
    """Check if URL points to a video file based on extension."""
    ...

def is_video_path(path: Path) -> bool:
    """Check if file path is a video file based on extension."""
    ...

def transform_input(input_data: Union[str, bytes, Path]): # -> dict[str, list[dict[str, str]]]:
    ...

def sanitize_multimodal_input(inputs: Union[TEXT, IMAGES]) -> List[Any]:
    """
    Sanitize the input to the embedding function.
    """
    ...

def sanitize_text_input(inputs: TEXT) -> List[str]:
    """
    Sanitize the input to the embedding function.
    """
    ...

@register("voyageai")
class VoyageAIEmbeddingFunction(EmbeddingFunction):
    """
    An embedding function that uses the VoyageAI API

    https://docs.voyageai.com/docs/embeddings

    Parameters
    ----------
    name: str
        The name of the model to use. List of acceptable models:

            * voyage-4 (1024 dims, general-purpose and multilingual retrieval)
            * voyage-4-lite (1024 dims, optimized for latency and cost)
            * voyage-4-large (1024 dims, best retrieval quality)
            * voyage-context-3
            * voyage-3.5
            * voyage-3.5-lite
            * voyage-3
            * voyage-3-lite
            * voyage-multimodal-3
            * voyage-multimodal-3.5
            * voyage-finance-2
            * voyage-multilingual-2
            * voyage-law-2
            * voyage-code-2

    output_dimension: int, optional
        The output dimension for models that support flexible dimensions.
        Currently only voyage-multimodal-3.5 supports this feature.
        Valid options: 256, 512, 1024 (default), 2048.

    Examples
    --------
    import lancedb
    from lancedb.pydantic import LanceModel, Vector
    from lancedb.embeddings import EmbeddingFunctionRegistry

    voyageai = EmbeddingFunctionRegistry
        .get_instance()
        .get("voyageai")
        .create(name="voyage-3")

    class TextModel(LanceModel):
        text: str = voyageai.SourceField()
        vector: Vector(voyageai.ndims()) =  voyageai.VectorField()

    data = [ { "text": "hello world" },
            { "text": "goodbye world" }]

    db = lancedb.connect("~/.lancedb")
    tbl = db.create_table("test", schema=TextModel, mode="overwrite")

    tbl.add(data)

    """
    name: str
    output_dimension: Optional[int] = ...
    client: ClassVar = ...
    _FLEXIBLE_DIM_MODELS: ClassVar[list] = ...
    _VALID_DIMENSIONS: ClassVar[list] = ...
    text_embedding_models: list = ...
    multimodal_embedding_models: list = ...
    contextual_embedding_models: list = ...
    def ndims(self): # -> int:
        ...
    
    def compute_query_embeddings(self, query: Union[str, PIL.Image.Image], *args, **kwargs) -> List[np.ndarray]:
        """
        Compute the embeddings for a given user query

        Parameters
        ----------
        query : Union[str, PIL.Image.Image]
            The query to embed. A query can be either text or an image.

        Returns
        -------
            List[np.array]: the list of embeddings
        """
        ...
    
    def compute_source_embeddings(self, inputs: Union[TEXT, IMAGES], *args, **kwargs) -> List[np.array]:
        """
        Compute the embeddings for the inputs

        Parameters
        ----------
        inputs : Union[TEXT, IMAGES]
            The inputs to embed. The input can be either str, bytes, Path (to an image),
            PIL.Image or list of these.

        Returns
        -------
            List[np.array]: the list of embeddings
        """
        ...
    


