"""
This type stub file was generated by pyright.
"""

import pyarrow as pa
from typing import Union
from lancedb._lancedb import PyExpr

"""Type-safe expression builder for filters and projections.

Instead of writing raw SQL strings you can build expressions with Python
operators::

    from lancedb.expr import col, lit

    # filter: age > 18 AND status = 'active'
    filt = (col("age") > lit(18)) & (col("status") == lit("active"))

    # projection: compute a derived column
    proj = {"score": col("raw_score") * lit(1.5)}

    table.search().where(filt).select(proj).to_list()
"""
__all__ = ["Expr", "col", "lit", "func"]
_STR_TO_PA_TYPE: dict = ...
ExprLike = Union["Expr", bool, int, float, str]
class Expr:
    """A type-safe expression node.

    Construct instances with :func:`col` and :func:`lit`, then combine them
    using Python operators or the named methods below.

    Examples
    --------
    >>> from lancedb.expr import col, lit
    >>> filt = (col("age") > lit(18)) & (col("name").lower() == lit("alice"))
    >>> proj = {"double": col("x") * lit(2)}
    """
    __hash__ = ...
    def __init__(self, inner: PyExpr) -> None:
        ...
    
    def __eq__(self, other: ExprLike) -> Expr:
        """Equal to (``col("x") == 1``)."""
        ...
    
    def __ne__(self, other: ExprLike) -> Expr:
        """Not equal to (``col("x") != 1``)."""
        ...
    
    def __lt__(self, other: ExprLike) -> Expr:
        """Less than (``col("x") < 1``)."""
        ...
    
    def __le__(self, other: ExprLike) -> Expr:
        """Less than or equal to (``col("x") <= 1``)."""
        ...
    
    def __gt__(self, other: ExprLike) -> Expr:
        """Greater than (``col("x") > 1``)."""
        ...
    
    def __ge__(self, other: ExprLike) -> Expr:
        """Greater than or equal to (``col("x") >= 1``)."""
        ...
    
    def __and__(self, other: Expr) -> Expr:
        """Logical AND (``expr_a & expr_b``)."""
        ...
    
    def __or__(self, other: Expr) -> Expr:
        """Logical OR (``expr_a | expr_b``)."""
        ...
    
    def __invert__(self) -> Expr:
        """Logical NOT (``~expr``)."""
        ...
    
    def __add__(self, other: ExprLike) -> Expr:
        """Add (``col("x") + 1``)."""
        ...
    
    def __radd__(self, other: ExprLike) -> Expr:
        """Right-hand add (``1 + col("x")``)."""
        ...
    
    def __sub__(self, other: ExprLike) -> Expr:
        """Subtract (``col("x") - 1``)."""
        ...
    
    def __rsub__(self, other: ExprLike) -> Expr:
        """Right-hand subtract (``1 - col("x")``)."""
        ...
    
    def __mul__(self, other: ExprLike) -> Expr:
        """Multiply (``col("x") * 2``)."""
        ...
    
    def __rmul__(self, other: ExprLike) -> Expr:
        """Right-hand multiply (``2 * col("x")``)."""
        ...
    
    def __truediv__(self, other: ExprLike) -> Expr:
        """Divide (``col("x") / 2``)."""
        ...
    
    def __rtruediv__(self, other: ExprLike) -> Expr:
        """Right-hand divide (``1 / col("x")``)."""
        ...
    
    def lower(self) -> Expr:
        """Convert string column values to lowercase."""
        ...
    
    def upper(self) -> Expr:
        """Convert string column values to uppercase."""
        ...
    
    def contains(self, substr: ExprLike) -> Expr:
        """Return True where the string contains *substr*."""
        ...
    
    def cast(self, data_type: Union[str, pa.DataType]) -> Expr:
        """Cast values to *data_type*.

        Parameters
        ----------
        data_type:
            A PyArrow ``DataType`` (e.g. ``pa.int32()``) or one of the type
            name strings: ``"bool"``, ``"int8"``, ``"int16"``, ``"int32"``,
            ``"int64"``, ``"uint8"``–``"uint64"``, ``"float32"``,
            ``"float64"``, ``"string"``, ``"date32"``, ``"date64"``.
        """
        ...
    
    def eq(self, other: ExprLike) -> Expr:
        """Equal to."""
        ...
    
    def ne(self, other: ExprLike) -> Expr:
        """Not equal to."""
        ...
    
    def lt(self, other: ExprLike) -> Expr:
        """Less than."""
        ...
    
    def lte(self, other: ExprLike) -> Expr:
        """Less than or equal to."""
        ...
    
    def gt(self, other: ExprLike) -> Expr:
        """Greater than."""
        ...
    
    def gte(self, other: ExprLike) -> Expr:
        """Greater than or equal to."""
        ...
    
    def and_(self, other: Expr) -> Expr:
        """Logical AND."""
        ...
    
    def or_(self, other: Expr) -> Expr:
        """Logical OR."""
        ...
    
    def to_sql(self) -> str:
        """Render the expression as a SQL string (useful for debugging)."""
        ...
    
    def __repr__(self) -> str:
        ...
    


def col(name: str) -> Expr:
    """Reference a table column by name.

    Parameters
    ----------
    name:
        The column name.

    Examples
    --------
    >>> from lancedb.expr import col, lit
    >>> col("age") > lit(18)
    Expr((age > 18))
    """
    ...

def lit(value: Union[bool, int, float, str]) -> Expr:
    """Create a literal (constant) value expression.

    Parameters
    ----------
    value:
        A Python ``bool``, ``int``, ``float``, or ``str``.

    Examples
    --------
    >>> from lancedb.expr import col, lit
    >>> col("price") * lit(1.1)
    Expr((price * 1.1))
    """
    ...

def func(name: str, *args: ExprLike) -> Expr:
    """Call an arbitrary SQL function by name.

    Parameters
    ----------
    name:
        The SQL function name (e.g. ``"lower"``, ``"upper"``).
    *args:
        The function arguments as :class:`Expr` or plain Python literals.

    Examples
    --------
    >>> from lancedb.expr import col, func
    >>> func("lower", col("name"))
    Expr(lower(name))
    """
    ...

