"""
This type stub file was generated by pyright.
"""

import sys
import pyarrow as pa
from typing import Dict, Iterable, List, Optional, Union
from overrides import override
from datetime import timedelta
from lancedb.db import DBConnection
from lancedb.io import StorageOptionsProvider
from lance_namespace import CreateNamespaceResponse, DescribeNamespaceResponse, DropNamespaceResponse, LanceNamespace, ListNamespacesResponse, ListTablesResponse
from lancedb.table import AsyncTable, Table
from lancedb.common import DATA
from lancedb.pydantic import LanceModel
from lancedb.embeddings import EmbeddingFunctionConfig
from ._lancedb import Session

"""
LanceDB Namespace integration module.

This module provides integration with lance_namespace for managing tables
through a namespace abstraction.
"""
if sys.version_info >= (3, 12):
    ...
else:
    ...
class LanceNamespaceStorageOptionsProvider(StorageOptionsProvider):
    """Storage options provider that fetches storage options from a LanceNamespace.

    This provider automatically fetches fresh storage options by calling the
    namespace's describe_table() method, which returns both the table location
    and time-limited storage options. This enables automatic credential refresh
    for tables accessed through namespace connections.

    Parameters
    ----------
    namespace : LanceNamespace
        The namespace instance with a describe_table() method
    table_id : List[str]
        The table identifier (namespace path + table name)

    Examples
    --------
    Create a provider and fetch storage options::

        from lance_namespace import connect as namespace_connect

        # Connect to namespace (requires a running namespace server)
        namespace = namespace_connect("rest", {"uri": "https://..."})
        provider = LanceNamespaceStorageOptionsProvider(
            namespace=namespace,
            table_id=["my_namespace", "my_table"]
        )
        options = provider.fetch_storage_options()
    """
    def __init__(self, namespace: LanceNamespace, table_id: List[str]) -> None:
        """Initialize with namespace and table ID.

        Parameters
        ----------
        namespace : LanceNamespace
            The namespace instance with a describe_table() method
        table_id : List[str]
            The table identifier
        """
        ...
    
    def fetch_storage_options(self) -> Dict[str, str]:
        """Fetch storage options from the namespace.

        This calls namespace.describe_table() to get the latest storage options
        and their expiration time.

        Returns
        -------
        Dict[str, str]
            Flat dictionary of string key-value pairs containing storage options.
            May include "expires_at_millis" key for automatic refresh.

        Raises
        ------
        RuntimeError
            If namespace does not return storage_options
        """
        ...
    
    def provider_id(self) -> str:
        """Return a human-readable unique identifier for this provider instance."""
        ...
    


class LanceNamespaceDBConnection(DBConnection):
    """
    A LanceDB connection that uses a namespace for table management.

    This connection delegates table URI resolution to a lance_namespace instance,
    while using the standard LanceTable for actual table operations.
    """
    def __init__(self, namespace: LanceNamespace, *, read_consistency_interval: Optional[timedelta] = ..., storage_options: Optional[Dict[str, str]] = ..., session: Optional[Session] = ...) -> None:
        """
        Initialize a namespace-based LanceDB connection.

        Parameters
        ----------
        namespace : LanceNamespace
            The namespace instance to use for table management
        read_consistency_interval : Optional[timedelta]
            The interval at which to check for updates to the table from other
            processes. If None, then consistency is not checked.
        storage_options : Optional[Dict[str, str]]
            Additional options for the storage backend
        session : Optional[Session]
            A session to use for this connection
        """
        ...
    
    @override
    def table_names(self, page_token: Optional[str] = ..., limit: int = ..., *, namespace: Optional[List[str]] = ...) -> Iterable[str]:
        """
        List table names in the database.

        .. deprecated::
            Use :meth:`list_tables` instead, which provides proper pagination support.
        """
        ...
    
    @override
    def create_table(self, name: str, data: Optional[DATA] = ..., schema: Optional[Union[pa.Schema, LanceModel]] = ..., mode: str = ..., exist_ok: bool = ..., on_bad_vectors: str = ..., fill_value: float = ..., embedding_functions: Optional[List[EmbeddingFunctionConfig]] = ..., *, namespace: Optional[List[str]] = ..., storage_options: Optional[Dict[str, str]] = ..., storage_options_provider: Optional[StorageOptionsProvider] = ..., data_storage_version: Optional[str] = ..., enable_v2_manifest_paths: Optional[bool] = ...) -> Table:
        ...
    
    @override
    def open_table(self, name: str, *, namespace: Optional[List[str]] = ..., storage_options: Optional[Dict[str, str]] = ..., storage_options_provider: Optional[StorageOptionsProvider] = ..., index_cache_size: Optional[int] = ...) -> Table:
        ...
    
    @override
    def drop_table(self, name: str, namespace: Optional[List[str]] = ...): # -> None:
        ...
    
    @override
    def rename_table(self, cur_name: str, new_name: str, cur_namespace: Optional[List[str]] = ..., new_namespace: Optional[List[str]] = ...):
        ...
    
    @override
    def drop_database(self):
        ...
    
    @override
    def drop_all_tables(self, namespace: Optional[List[str]] = ...): # -> None:
        ...
    
    @override
    def list_namespaces(self, namespace: Optional[List[str]] = ..., page_token: Optional[str] = ..., limit: Optional[int] = ...) -> ListNamespacesResponse:
        """
        List child namespaces under the given namespace.

        Parameters
        ----------
        namespace : Optional[List[str]]
            The parent namespace to list children from.
            If None, lists root-level namespaces.
        page_token : Optional[str]
            Token for pagination. Use the token from a previous response
            to get the next page of results.
        limit : int, optional
            Maximum number of namespaces to return.

        Returns
        -------
        ListNamespacesResponse
            Response containing namespace names and optional page_token for pagination.
        """
        ...
    
    @override
    def create_namespace(self, namespace: List[str], mode: Optional[str] = ..., properties: Optional[Dict[str, str]] = ...) -> CreateNamespaceResponse:
        """
        Create a new namespace.

        Parameters
        ----------
        namespace : List[str]
            The namespace path to create.
        mode : str, optional
            Creation mode - "create" (fail if exists), "exist_ok" (skip if exists),
            or "overwrite" (replace if exists). Case insensitive.
        properties : Dict[str, str], optional
            Properties to set on the namespace.

        Returns
        -------
        CreateNamespaceResponse
            Response containing the properties of the created namespace.
        """
        ...
    
    @override
    def drop_namespace(self, namespace: List[str], mode: Optional[str] = ..., behavior: Optional[str] = ...) -> DropNamespaceResponse:
        """
        Drop a namespace.

        Parameters
        ----------
        namespace : List[str]
            The namespace path to drop.
        mode : str, optional
            Whether to skip if not exists ("SKIP") or fail ("FAIL"). Case insensitive.
        behavior : str, optional
            Whether to restrict drop if not empty ("RESTRICT") or cascade ("CASCADE").
            Case insensitive.

        Returns
        -------
        DropNamespaceResponse
            Response containing properties and transaction_id if applicable.
        """
        ...
    
    @override
    def describe_namespace(self, namespace: List[str]) -> DescribeNamespaceResponse:
        """
        Describe a namespace.

        Parameters
        ----------
        namespace : List[str]
            The namespace identifier to describe.

        Returns
        -------
        DescribeNamespaceResponse
            Response containing the namespace properties.
        """
        ...
    
    @override
    def list_tables(self, namespace: Optional[List[str]] = ..., page_token: Optional[str] = ..., limit: Optional[int] = ...) -> ListTablesResponse:
        """
        List all tables in this database with pagination support.

        Parameters
        ----------
        namespace : List[str], optional
            The namespace to list tables in.
            None or empty list represents root namespace.
        page_token : str, optional
            Token for pagination. Use the token from a previous response
            to get the next page of results.
        limit : int, optional
            The maximum number of results to return.

        Returns
        -------
        ListTablesResponse
            Response containing table names and optional page_token for pagination.
        """
        ...
    


class AsyncLanceNamespaceDBConnection:
    """
    An async LanceDB connection that uses a namespace for table management.

    This connection delegates table URI resolution to a lance_namespace instance,
    while providing async methods for all operations.
    """
    def __init__(self, namespace: LanceNamespace, *, read_consistency_interval: Optional[timedelta] = ..., storage_options: Optional[Dict[str, str]] = ..., session: Optional[Session] = ...) -> None:
        """
        Initialize an async namespace-based LanceDB connection.

        Parameters
        ----------
        namespace : LanceNamespace
            The namespace instance to use for table management
        read_consistency_interval : Optional[timedelta]
            The interval at which to check for updates to the table from other
            processes. If None, then consistency is not checked.
        storage_options : Optional[Dict[str, str]]
            Additional options for the storage backend
        session : Optional[Session]
            A session to use for this connection
        """
        ...
    
    async def table_names(self, page_token: Optional[str] = ..., limit: int = ..., *, namespace: Optional[List[str]] = ...) -> Iterable[str]:
        """
        List table names in the namespace.

        .. deprecated::
            Use :meth:`list_tables` instead, which provides proper pagination support.
        """
        ...
    
    async def create_table(self, name: str, data: Optional[DATA] = ..., schema: Optional[Union[pa.Schema, LanceModel]] = ..., mode: str = ..., exist_ok: bool = ..., on_bad_vectors: str = ..., fill_value: float = ..., embedding_functions: Optional[List[EmbeddingFunctionConfig]] = ..., *, namespace: Optional[List[str]] = ..., storage_options: Optional[Dict[str, str]] = ..., storage_options_provider: Optional[StorageOptionsProvider] = ..., data_storage_version: Optional[str] = ..., enable_v2_manifest_paths: Optional[bool] = ...) -> AsyncTable:
        """Create a new table in the namespace."""
        ...
    
    async def open_table(self, name: str, *, namespace: Optional[List[str]] = ..., storage_options: Optional[Dict[str, str]] = ..., storage_options_provider: Optional[StorageOptionsProvider] = ..., index_cache_size: Optional[int] = ...) -> AsyncTable:
        """Open an existing table from the namespace."""
        ...
    
    async def drop_table(self, name: str, namespace: Optional[List[str]] = ...): # -> None:
        """Drop a table from the namespace."""
        ...
    
    async def rename_table(self, cur_name: str, new_name: str, cur_namespace: Optional[List[str]] = ..., new_namespace: Optional[List[str]] = ...):
        """Rename is not supported for namespace connections."""
        ...
    
    async def drop_database(self):
        """Deprecated method."""
        ...
    
    async def drop_all_tables(self, namespace: Optional[List[str]] = ...): # -> None:
        """Drop all tables in the namespace."""
        ...
    
    async def list_namespaces(self, namespace: Optional[List[str]] = ..., page_token: Optional[str] = ..., limit: Optional[int] = ...) -> ListNamespacesResponse:
        """
        List child namespaces under the given namespace.

        Parameters
        ----------
        namespace : Optional[List[str]]
            The parent namespace to list children from.
            If None, lists root-level namespaces.
        page_token : Optional[str]
            Token for pagination. Use the token from a previous response
            to get the next page of results.
        limit : int, optional
            Maximum number of namespaces to return.

        Returns
        -------
        ListNamespacesResponse
            Response containing namespace names and optional page_token for pagination.
        """
        ...
    
    async def create_namespace(self, namespace: List[str], mode: Optional[str] = ..., properties: Optional[Dict[str, str]] = ...) -> CreateNamespaceResponse:
        """
        Create a new namespace.

        Parameters
        ----------
        namespace : List[str]
            The namespace path to create.
        mode : str, optional
            Creation mode - "create" (fail if exists), "exist_ok" (skip if exists),
            or "overwrite" (replace if exists). Case insensitive.
        properties : Dict[str, str], optional
            Properties to set on the namespace.

        Returns
        -------
        CreateNamespaceResponse
            Response containing the properties of the created namespace.
        """
        ...
    
    async def drop_namespace(self, namespace: List[str], mode: Optional[str] = ..., behavior: Optional[str] = ...) -> DropNamespaceResponse:
        """
        Drop a namespace.

        Parameters
        ----------
        namespace : List[str]
            The namespace path to drop.
        mode : str, optional
            Whether to skip if not exists ("SKIP") or fail ("FAIL"). Case insensitive.
        behavior : str, optional
            Whether to restrict drop if not empty ("RESTRICT") or cascade ("CASCADE").
            Case insensitive.

        Returns
        -------
        DropNamespaceResponse
            Response containing properties and transaction_id if applicable.
        """
        ...
    
    async def describe_namespace(self, namespace: List[str]) -> DescribeNamespaceResponse:
        """
        Describe a namespace.

        Parameters
        ----------
        namespace : List[str]
            The namespace identifier to describe.

        Returns
        -------
        DescribeNamespaceResponse
            Response containing the namespace properties.
        """
        ...
    
    async def list_tables(self, namespace: Optional[List[str]] = ..., page_token: Optional[str] = ..., limit: Optional[int] = ...) -> ListTablesResponse:
        """
        List all tables in this database with pagination support.

        Parameters
        ----------
        namespace : List[str], optional
            The namespace to list tables in.
            None or empty list represents root namespace.
        page_token : str, optional
            Token for pagination. Use the token from a previous response
            to get the next page of results.
        limit : int, optional
            The maximum number of results to return.

        Returns
        -------
        ListTablesResponse
            Response containing table names and optional page_token for pagination.
        """
        ...
    


def connect_namespace(impl: str, properties: Dict[str, str], *, read_consistency_interval: Optional[timedelta] = ..., storage_options: Optional[Dict[str, str]] = ..., session: Optional[Session] = ...) -> LanceNamespaceDBConnection:
    """
    Connect to a LanceDB database through a namespace.

    Parameters
    ----------
    impl : str
        The namespace implementation to use. For examples:
        - "dir" for DirectoryNamespace
        - "rest" for REST-based namespace
        - Full module path for custom implementations
    properties : Dict[str, str]
        Configuration properties for the namespace implementation.
        Different namespace implemenation has different config properties.
        For example, use DirectoryNamespace with {"root": "/path/to/directory"}
    read_consistency_interval : Optional[timedelta]
        The interval at which to check for updates to the table from other
        processes. If None, then consistency is not checked.
    storage_options : Optional[Dict[str, str]]
        Additional options for the storage backend
    session : Optional[Session]
        A session to use for this connection

    Returns
    -------
    LanceNamespaceDBConnection
        A namespace-based connection to LanceDB
    """
    ...

def connect_namespace_async(impl: str, properties: Dict[str, str], *, read_consistency_interval: Optional[timedelta] = ..., storage_options: Optional[Dict[str, str]] = ..., session: Optional[Session] = ...) -> AsyncLanceNamespaceDBConnection:
    """
    Connect to a LanceDB database through a namespace (returns async connection).

    This function is synchronous but returns an AsyncLanceNamespaceDBConnection
    that provides async methods for all database operations.

    Parameters
    ----------
    impl : str
        The namespace implementation to use. For examples:
        - "dir" for DirectoryNamespace
        - "rest" for REST-based namespace
        - Full module path for custom implementations
    properties : Dict[str, str]
        Configuration properties for the namespace implementation.
        Different namespace implemenation has different config properties.
        For example, use DirectoryNamespace with {"root": "/path/to/directory"}
    read_consistency_interval : Optional[timedelta]
        The interval at which to check for updates to the table from other
        processes. If None, then consistency is not checked.
    storage_options : Optional[Dict[str, str]]
        Additional options for the storage backend
    session : Optional[Session]
        A session to use for this connection

    Returns
    -------
    AsyncLanceNamespaceDBConnection
        An async namespace-based connection to LanceDB

    Examples
    --------
    >>> import lancedb
    >>> # This function is sync, but returns an async connection
    >>> db = lancedb.connect_namespace_async("dir", {"root": "/path/to/db"})
    >>> # Use async methods on the connection
    >>> async def use_db():
    ...     tables = await db.table_names()
    ...     table = await db.create_table("my_table", schema=schema)
    """
    ...

