"""
This type stub file was generated by pyright.
"""

import pyarrow as pa
from deprecation import deprecated
from lancedb import AsyncConnection, DBConnection
from ._lancedb import PermutationReader
from .table import LanceTable
from typing import Any, Callable, Iterator, Literal, Optional, TYPE_CHECKING, Union
from lancedb.dependencies import numpy as np, pandas as pd, polars as pl

if TYPE_CHECKING:
    ...
class PermutationBuilder:
    """
    A utility for creating a "permutation table" which is a table that defines an
    ordering on a base table.

    The permutation table does not store the actual data.  It only stores row
    ids and split ids to define the ordering.  The [Permutation] class can be used to
    read the data from the base table in the order defined by the permutation table.

    Permutations can split, shuffle, and filter the data in the base table.

    A filter limits the rows that are included in the permutation.
    Splits divide the data into subsets (for example, a test/train split, or K
    different splits for cross-validation).
    Shuffling randomizes the order of the rows in the permutation.

    Splits can optionally be named.  If names are provided it will enable them to
    be referenced by name in the future.  If names are not provided then they can only
    be referenced by their ordinal index.  There is no requirement to name every split.

    By default, the permutation will be stored in memory and will be lost when the
    program exits.  To persist the permutation (for very large datasets or to share
    the permutation across multiple workers) use the [persist](#persist) method to
    create a permanent table.
    """
    def __init__(self, table: LanceTable) -> None:
        """
        Creates a new permutation builder for the given table.

        By default, the permutation builder will create a single split that contains all
        rows in the same order as the base table.
        """
        ...
    
    def persist(self, database: Union[DBConnection, AsyncConnection], table_name: str) -> PermutationBuilder:
        """
        Persist the permutation to the given database.
        """
        ...
    
    def split_random(self, *, ratios: Optional[list[float]] = ..., counts: Optional[list[int]] = ..., fixed: Optional[int] = ..., seed: Optional[int] = ..., split_names: Optional[list[str]] = ...) -> PermutationBuilder:
        """
        Configure random splits for the permutation.

        One of ratios, counts, or fixed must be provided.

        If ratios are provided, they will be used to determine the relative size of each
        split. For example, if ratios are [0.3, 0.7] then the first split will contain
        30% of the rows and the second split will contain 70% of the rows.

        If counts are provided, they will be used to determine the absolute number of
        rows in each split. For example, if counts are [100, 200] then the first split
        will contain 100 rows and the second split will contain 200 rows.

        If fixed is provided, it will be used to determine the number of splits.
        For example, if fixed is 3 then the permutation will be split evenly into 3
        splits.

        Rows will be randomly assigned to splits.  The optional seed can be provided to
        make the assignment deterministic.

        The optional split_names can be provided to name the splits.  If not provided,
        the splits can only be referenced by their index.
        """
        ...
    
    def split_hash(self, columns: list[str], split_weights: list[int], *, discard_weight: Optional[int] = ..., split_names: Optional[list[str]] = ...) -> PermutationBuilder:
        """
        Configure hash-based splits for the permutation.

        First, a hash will be calculated over the specified columns.  The splits weights
        are then used to determine how many rows to assign to each split.  For example,
        if split weights are [1, 2] then the first split will contain 1/3 of the rows
        and the second split will contain 2/3 of the rows.

        The optional discard weight can be provided to determine what percentage of rows
        should be discarded.  For example, if split weights are [1, 2] and discard
        weight is 1 then 25% of the rows will be discarded.

        Hash-based splits are useful if you want the split to be more or less random but
        you don't want the split assignments to change if rows are added or removed
        from the table.

        The optional split_names can be provided to name the splits.  If not provided,
        the splits can only be referenced by their index.
        """
        ...
    
    def split_sequential(self, *, ratios: Optional[list[float]] = ..., counts: Optional[list[int]] = ..., fixed: Optional[int] = ..., split_names: Optional[list[str]] = ...) -> PermutationBuilder:
        """
        Configure sequential splits for the permutation.

        One of ratios, counts, or fixed must be provided.

        If ratios are provided, they will be used to determine the relative size of each
        split. For example, if ratios are [0.3, 0.7] then the first split will contain
        30% of the rows and the second split will contain 70% of the rows.

        If counts are provided, they will be used to determine the absolute number of
        rows in each split. For example, if counts are [100, 200] then the first split
        will contain 100 rows and the second split will contain 200 rows.

        If fixed is provided, it will be used to determine the number of splits.
        For example, if fixed is 3 then the permutation will be split evenly into 3
        splits.

        Rows will be assigned to splits sequentially.  The first N1 rows are assigned to
        split 1, the next N2 rows are assigned to split 2, etc.

        The optional split_names can be provided to name the splits.  If not provided,
        the splits can only be referenced by their index.
        """
        ...
    
    def split_calculated(self, calculation: str, split_names: Optional[list[str]] = ...) -> PermutationBuilder:
        """
        Use pre-calculated splits for the permutation.

        The calculation should be an SQL statement that returns an integer value between
        0 and the number of splits - 1.  For example, if you have 3 splits then the
        calculation should return 0 for the first split, 1 for the second split, and 2
        for the third split.

        This can be used to implement any kind of user-defined split strategy.

        The optional split_names can be provided to name the splits.  If not provided,
        the splits can only be referenced by their index.
        """
        ...
    
    def shuffle(self, *, seed: Optional[int] = ..., clump_size: Optional[int] = ...) -> PermutationBuilder:
        """
        Randomly shuffle the rows in the permutation.

        An optional seed can be provided to make the shuffle deterministic.

        If a clump size is provided, then data will be shuffled as small "clumps"
        of contiguous rows.  This allows for a balance between randomization and
        I/O performance.  It can be useful when reading from cloud storage.
        """
        ...
    
    def filter(self, filter: str) -> PermutationBuilder:
        """
        Configure a filter for the permutation.

        The filter should be an SQL statement that returns a boolean value for each row.
        Only rows where the filter is true will be included in the permutation.
        """
        ...
    
    def execute(self) -> LanceTable:
        """
        Execute the configuration and create the permutation table.
        """
        ...
    


def permutation_builder(table: LanceTable) -> PermutationBuilder:
    ...

class Permutations:
    """
    A collection of permutations indexed by name or ordinal index.

    Splits are defined when the permutation is created.  Splits can always be referenced
    by their ordinal index.  If names were provided when the permutation was created
    then they can also be referenced by name.

    Each permutation or "split" is a view of a portion of the base table.  For more
    details see [Permutation].

    Attributes
    ----------
    base_table: LanceTable
        The base table that the permutations are based on.
    permutation_table: LanceTable
        The permutation table that defines the splits.
    split_names: list[str]
        The names of the splits.
    split_dict: dict[str, int]
        A dictionary mapping split names to their ordinal index.

    Examples
    --------
    >>> # Initial data
    >>> import lancedb
    >>> db = lancedb.connect("memory:///")
    >>> tbl = db.create_table("tbl", data=[{"x": x} for x in range(1000)])
    >>> # Create a permutation
    >>> perm_tbl = (
    ...    permutation_builder(tbl)
    ...    .split_random(ratios=[0.95, 0.05], split_names=["train", "test"])
    ...    .shuffle()
    ...    .execute()
    ... )
    >>> # Read the permutations
    >>> permutations = Permutations(tbl, perm_tbl)
    >>> permutations["train"]
    <lancedb.permutation.Permutation ...>
    >>> permutations[0]
    <lancedb.permutation.Permutation ...>
    >>> permutations.split_names
    ['train', 'test']
    >>> permutations.split_dict
    {'train': 0, 'test': 1}
    """
    def __init__(self, base_table: LanceTable, permutation_table: LanceTable) -> None:
        ...
    
    def get_by_name(self, name: str) -> Permutation:
        """
        Get a permutation by name.

        If no split named `name` is found then an error will be raised.
        """
        ...
    
    def get_by_index(self, index: int) -> Permutation:
        """
        Get a permutation by index.
        """
        ...
    
    def __getitem__(self, name: Union[str, int]) -> Permutation:
        ...
    


class Transforms:
    """
    Namespace for common transformation functions
    """
    @staticmethod
    def arrow2python(batch: pa.RecordBatch) -> list[dict[str, Any]]:
        ...
    
    @staticmethod
    def arrow2pythoncol(batch: pa.RecordBatch) -> dict[str, list[Any]]:
        ...
    
    @staticmethod
    def arrow2arrow(batch: pa.RecordBatch) -> pa.RecordBatch:
        ...
    
    @staticmethod
    def arrow2numpy(batch: pa.RecordBatch) -> np.ndarray:
        ...
    
    @staticmethod
    def arrow2pandas(batch: pa.RecordBatch) -> pd.DataFrame:
        ...
    
    @staticmethod
    def arrow2polars() -> pl.DataFrame:
        ...
    


DEFAULT_BATCH_SIZE = ...
class Permutation:
    """
    A Permutation is a view of a dataset that can be used as input to model training
    and evaluation.

    A Permutation fulfills the pytorch Dataset contract and is loosely modeled after the
    huggingface Dataset so it should be easy to use with existing code.

    A permutation is not a "materialized view" or copy of the underlying data.  It is
    calculated on the fly from the base table.  As a result, it is truly "lazy" and does
    not require materializing the entire dataset in memory.
    """
    def __init__(self, reader: PermutationReader, selection: dict[str, str], batch_size: int, transform_fn: Callable[pa.RecordBatch, Any]) -> None:
        """
        Internal constructor.  Use [from_tables](#from_tables) instead.
        """
        ...
    
    def with_batch_size(self, batch_size: int) -> Permutation:
        """
        Creates a new permutation with the given batch size
        """
        ...
    
    @classmethod
    def identity(cls, table: LanceTable) -> Permutation:
        """
        Creates an identity permutation for the given table.
        """
        ...
    
    @classmethod
    def from_tables(cls, base_table: LanceTable, permutation_table: Optional[LanceTable] = ..., split: Optional[Union[str, int]] = ...) -> Permutation:
        """
        Creates a permutation from the given base table and permutation table.

        A permutation table identifies which rows, and in what order, the data should
        be read from the base table.  For more details see the [PermutationBuilder]
        class.

        If no permutation table is provided, then the identity permutation will be
        created.  An identity permutation is a permutation that reads all rows in the
        base table in the order they are stored.

        The split parameter identifies which split to use.  If no split is provided
        then the first split will be used.
        """
        ...
    
    @property
    def schema(self) -> pa.Schema:
        ...
    
    @property
    def num_columns(self) -> int:
        """
        The number of columns in the permutation
        """
        ...
    
    @property
    def num_rows(self) -> int:
        """
        The number of rows in the permutation
        """
        ...
    
    @property
    def column_names(self) -> list[str]:
        """
        The names of the columns in the permutation
        """
        ...
    
    @property
    def shape(self) -> tuple[int, int]:
        """
        The shape of the permutation

        This will return self.num_rows, self.num_columns
        """
        ...
    
    def __len__(self) -> int:
        """
        The number of rows in the permutation

        This is an alias for [num_rows][lancedb.permutation.Permutation.num_rows]
        """
        ...
    
    def unique(self, _column: str) -> list[Any]:
        """
        Get the unique values in the given column
        """
        ...
    
    def flatten(self) -> Permutation:
        """
        Flatten the permutation

        Each column with a struct type will be flattened into multiple columns.

        This flattening operation happens at read time as a post-processing step
        so this call is cheap and no data is copied or modified in the underlying
        dataset.
        """
        ...
    
    def remove_columns(self, columns: list[str]) -> Permutation:
        """
        Remove the given columns from the permutation

        Note: this does not actually modify the underlying dataset.  It only changes
        which columns are visible from this permutation.  Also, this does not introduce
        a post-processing step.  Instead, we simply do not read those columns in the
        first place.

        If any of the provided columns does not exist in the current permutation then it
        will be ignored (no error is raised for missing columns)

        Returns a new permutation with the given columns removed.  This does not modify
        self.
        """
        ...
    
    def rename_column(self, old_name: str, new_name: str) -> Permutation:
        """
        Rename a column in the permutation

        If there is no column named old_name then an error will be raised
        If there is already a column named new_name then an error will be raised

        Note: this does not actually modify the underlying dataset.  It only changes
        the name of the column that is visible from this permutation.  This is a
        post-processing step but done at the batch level and so it is very cheap.
        No data will be copied.
        """
        ...
    
    def rename_columns(self, column_map: dict[str, str]) -> Permutation:
        """
        Rename the given columns in the permutation

        If any of the columns do not exist then an error will be raised
        If any of the new names already exist then an error will be raised

        Note: this does not actually modify the underlying dataset.  It only changes
        the name of the column that is visible from this permutation.  This is a
        post-processing step but done at the batch level and so it is very cheap.
        No data will be copied.
        """
        ...
    
    def select_columns(self, columns: list[str]) -> Permutation:
        """
        Select the given columns from the permutation

        This method refines the current selection, potentially removing columns.  It
        will not add back columns that were previously removed.

        If any of the columns do not exist then an error will be raised

        This does not introduce a post-processing step.  It simply reduces the amount
        of data we read.
        """
        ...
    
    def __iter__(self) -> Iterator[dict[str, Any]]:
        """
        Iterate over the permutation
        """
        ...
    
    def iter(self, batch_size: int, skip_last_batch: bool = ...) -> Iterator[dict[str, Any]]:
        """
        Iterate over the permutation in batches

        If skip_last_batch is True, the last batch will be skipped if it is not a
        multiple of batch_size.
        """
        ...
    
    def with_format(self, format: Literal["numpy", "python", "python_col", "pandas", "arrow", "torch", "torch_col", "polars",]) -> Permutation:
        """
        Set the format for batches

        If this method is not called, the "python" format will be used.

        The format can be one of:
        - "numpy" - the batch will be a dict of numpy arrays (one per column)
        - "python" - the batch will be a list of dicts (one per row)
        - "python_col" - the batch will be a dict of lists (one entry per column)
        - "pandas" - the batch will be a pandas DataFrame
        - "arrow" - the batch will be a pyarrow RecordBatch
        - "torch" - the batch will be a list of tensors, one per row
        - "torch_col" - the batch will be a 2D torch tensor (first dim indexes columns)
        - "polars" - the batch will be a polars DataFrame

        Conversion may or may not involve a data copy.  Lance uses Arrow internally
        and so it is able to zero-copy to the arrow and polars formats.

        Conversion to torch_col will be zero-copy but will only support a subset of data
        types (numeric types).

        Conversion to numpy and/or pandas will typically be zero-copy for numeric
        types.  Conversion of strings, lists, and structs will require creating python
        objects and this is not zero-copy.

        For custom formatting, use [with_transform](#with_transform) which overrides
        this method.
        """
        ...
    
    def with_transform(self, transform: Callable[pa.RecordBatch, Any]) -> Permutation:
        """
        Set a custom transform for the permutation

        The transform is a callable that will be invoked with each record batch.  The
        return value will be used as the batch for iteration.

        Note: transforms are not invoked in parallel.  This method is not a good place
        for expensive operations such as image decoding.
        """
        ...
    
    def __getitem__(self, index: int) -> Any:
        """
        Returns a single row from the permutation by offset
        """
        ...
    
    def __getitems__(self, indices: list[int]) -> Any:
        """
        Returns rows from the permutation by offset
        """
        ...
    
    @deprecated(details="Use with_skip instead")
    def skip(self, skip: int) -> Permutation:
        """
        Skip the first `skip` rows of the permutation

        Note: this method returns a new permutation and does not modify `self`
        It is provided for compatibility with the huggingface Dataset API.

        Use [with_skip](#with_skip) instead to avoid confusion.
        """
        ...
    
    def with_skip(self, skip: int) -> Permutation:
        """
        Skip the first `skip` rows of the permutation
        """
        ...
    
    @deprecated(details="Use with_take instead")
    def take(self, limit: int) -> Permutation:
        """
        Limit the permutation to `limit` rows (following any `skip`)

        Note: this method returns a new permutation and does not modify `self`
        It is provided for compatibility with the huggingface Dataset API.

        Use [with_take](#with_take) instead to avoid confusion.
        """
        ...
    
    def with_take(self, limit: int) -> Permutation:
        """
        Limit the permutation to `limit` rows (following any `skip`)
        """
        ...
    
    @deprecated(details="Use with_repeat instead")
    def repeat(self, times: int) -> Permutation:
        """
        Repeat the permutation `times` times

        Note: this method returns a new permutation and does not modify `self`
        It is provided for compatibility with the huggingface Dataset API.

        Use [with_repeat](#with_repeat) instead to avoid confusion.
        """
        ...
    
    def with_repeat(self, times: int) -> Permutation:
        """
        Repeat the permutation `times` times
        """
        ...
    


