"""
This type stub file was generated by pyright.
"""

import pyarrow as pa
from dataclasses import dataclass
from functools import singledispatch
from typing import Callable, Optional

@dataclass
class Scannable:
    schema: pa.Schema
    num_rows: Optional[int]
    reader: Callable[[], pa.RecordBatchReader]
    rescannable: bool = ...


@singledispatch
def to_scannable(data) -> Scannable:
    ...

_registered_modules: set[str] = ...
